# fly.toml app configuration file generated for fastapimicroserviceforsearch on 2026-03-03T10:09:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastapimicroserviceforsearch'
primary_region = 'dfw'

[build]

[processes]
  app = "/app/.venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
